### ISSUE TITLE
waiter.proto-test/test-h2-backend-proto-service is failing

### ISSUE THREAD

**Issue by shamsimam** [twosigma/waiter#1137]
Assertion logs:
```
FAIL in (test-h2-backend-proto-service) (proto_test.clj:60)
waiter.proto-test/test-h2-backend-proto-service
[CID=test-wptthbps-ae09531654-170f9beddc580e56, server=waiter/4e44f7f] Expected status: 200, actual: 502
Body:
  Waiter Error 502
  ================
  
    Request to service backend failed
  
  Request Info
  ============
  
            Host: 127.0.0.1:9091
            Path: /request-info
    Query String: 
          Method: POST
             CID: test-wptthbps-ae09531654-170f9beddc580e56
            Time: 2020-06-26T18:04:03.855Z
       Principal: travis
      Service Id: waiter-service-wptthbps747480687679-9260f347d00382bb084d25cc2be3da0b
```

Nginx logs:
```
2020/06/26 18:04:08 [info] 11363#11363: *3 client closed connection while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:10526
```

Waiter logs:
```
2020-06-26 18:04:08,427 WARN  org.eclipse.jetty.io.SelectorManager [waiter-client-http2-32] -  Exception while notifying connection SslConnection@48d581a3::SocketChannelEndPoint@7c72bb7d{/127.0.0.9:10526<->/127.0.0.1:60950,CLOSED,fill=-,flush=-,to=0/0}{io=1/1,kio=-1,kro=-1}->SslConnection@48d581a3{NEED_UNWRAP,eio=-1/-1,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@5bc367d8{/127.0.0.9:10526<->/127.0.0.1:60950,CLOSED,fill=-,flush=-,to=32/0}=>ALPNClientConnection@261cff83
java.lang.NoSuchFieldError: nullSession
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1350)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1117)
	at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:736)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1232)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1185)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:891)
	at org.eclipse.jetty.io.NegotiatingClientConnection.onOpen(NegotiatingClientConnection.java:63)
	at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:282)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:270)
	at org.eclipse.jetty.io.ManagedSelector.access$1900(ManagedSelector.java:61)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:923)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shamsimam** [comment]
This is a known issue with OpenJDK 8u252 and Jetty.

- https://issues.jenkins-ci.org/browse/JENKINS-62068
- https://github.com/jetty-project/jetty-alpn/issues/30

**Comment by shamsimam** [comment]
We will revisit this issue after upgrading Jetty 9.4.31 and/or JDK 11.
